name: CI (master)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
          os:
            - ubuntu-latest
            - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Check format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
